NoPermission: '&6[ConfigMessage] &cYou don''t have permission to do this!'
Food: 'Potato'
Number: 125
Boolean: true
FoodList:
  - 'Pizza'
  - 'Orange'
  - 'Grape'
Fly:
  Enable: '&6[ConfigMessage] &aFly has been enabled!'
  Disable: '&6[ConfigMessage] &cFly has been disabled!'
TPBowDisplayname: '&b&lTeleport Bow'
TPBowTeleportMessage: '&6[ConfigMessage] &6Swooosh!'
GiveTPBowOnJoin: true
WitherSpawning: false
PlayerMove: true
WitherSpawnAttempt: '&cWither Spawning is disabled'
Ores:
  - DIAMOND_ORE
  - EMERALD_ORE
create-message: '&aCreated armor stand!'
RTP:
  worldborder: true #True if you want to limit how far players teleport
  border: 1000
Motd:
  enabled: true
  message:
    - '&bline1'
    - '&eline2'
    - '&cline3'
Launchpad:
  enabled: true
  topblock: STONE_PRESSURE_PLATE
  bottomblock: REDSTONE_BLOCK